# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba61b54fe08cd865d72686f6f075730e1ef4720b2f1fe5c3e7893efd3420e5b49358556728501ba487b168b4ff41cb8155f086cb79c5f56751f7f24902e7ead

test:
  secret_key_base: 5207c7d173e3d8cf4d443f9b72b9e6fd6aaf79832f3eb1f0d960a4a191810259079cf6135205f9a1755ff13275965c9c283f955556939434d93add66e3484c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
